### PR TITLE
Added support to dump creation stack trace

### PR DESCRIPTION
**Pull request by chivandikwa**
While it is useful to see the undiposed objects it can be very difficult to track were they are coming from especially in a large solution. I have added the option to choose to have the creation stack trace dumped alongside each object on dumping the undisposed object details.

[Review on Reviewable](https://reviewable.io/reviews/ermshiperete/undisposed-fody/2)

### CODE REVIEW

**Comment by ermshiperete** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[Undisposed/DisposeTracker.cs, line 68 [r1]](https://reviewable.io:443/reviews/ermshiperete/undisposed-fody/2#-KCF6W1J_m8EgNOSYTzl:-KCF6W1J_m8EgNOSYTzm:-420511678) ([raw file](https://github.com/ermshiperete/undisposed-fody/blob/764778af88f11612bffbb5b73e9b3a592ac997d2/Undisposed/DisposeTracker.cs#L68)):_
Shouldn't we pass `'\n'` instead of `string.Empty` as first parameter so that the new stacktrace will show up in multiple lines?

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ermshiperete/undisposed-fody/2)_

**Comment by chivandikwa** [comment]
'\n' over string.Empty will result in black line between each frame in the stack trace.

**Comment by ermshiperete** [comment]
That doesn't work for me. I don't get a black line.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ermshiperete/undisposed-fody/2#-:-KCKSvbYvu_RFS_MklFj:-1659081653)_

**Comment by ermshiperete** [comment]
I applied a slightly modified version. Thanks for your contributions!

**Comment by chivandikwa** [comment]
Thanks for the modification and for taking time to review and accept the pull request.

**Pull request closed without merging**
